#server:
#  port: ${PORT:8083}

spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: catalog-service
#  datasource:
#    url: jdbc:h2:~/movie;AUTO_SERVER=TRUE
#    username: sa
#    password: sa
#    drive-class-name: org.h2.driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#      jdbc:
#        time_zone: UTC-3